### ISSUE TITLE
Release GHA crashes for webpage build

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#96]
The new GHA workflow `release.yml` for automatic releases upon mergin of PR does two things: 

1. Packages all DeerLab files and creates a new release with a new tag
2. Build the webpage and deploys it to GH-Pages (equal to `deploy_ghpages.yml`)

Step 1 is accomplished without problem, however there seems to be a problem with Step 2. While the second step uses the same code as ``deploy_ghpages.yml``, in `release.yml` I get the following error:

````
Run cd build
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/DeerLab/DeerLab/build/multiversedocs.py", line 34, in <module>
    mostrecent = subprocess.check_output (["git", "describe", "--tags", "--abbrev=0"])
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--abbrev=0']' returned non-zero exit status 128.
##[error]Process completed with exit code 1.
````

It might be that the previous step in `release.yml` removes the checkedout copy of DeerLab on the GHA VM upon release. 

This must be fixed prior to the next release.

**Comment by luisfabib** [comment]
The issue arises in `multiversedocs.py` when calling ``git describe`` which leads to the error

    fatal: No names found, cannot describe anything.

This means that `git describe` is not finding any tags in the cloned repository. Probably this is due to GitHub Actions using a shallow clone at that point.
